# Generated by Django 5.0.4 on 2024-04-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_customuser_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
